name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3  # Use v3 to get the latest version
        with:
          node-version: '18'  # Update to Node.js 18
      
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.2.0

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1.2.0
        with:
          solution-file: out/CustomDialogAccelerator.zip
          solution-folder: ./package
          solution-type: Both
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: CustomDialogAccelerator.zip
          path: out/
  release:
    name: Upload Build Artifact
    runs-on: windows-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0.0.${{ github.run_number }}
          release_name: Release-v1.0.0.${{ github.run_number }}
          body: |
            Changes in this Release:
            - $(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.before }}...${{ github.sha }}" -H "Authorization: Bearer ${{ secrets.PAT }}" | jq -r '.title + "\n" + .body')

          draft: false
          prerelease: false     
       
