name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Solution
    runs-on: windows-latest   # alternate runner OS is: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.2.0

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1.2.0
        with:
          solution-file: out/CustomDialogAccelerator.zip
          solution-folder: ./package
          solution-type: Both

  release:
    name: Upload Build Artifact
    runs-on: windows-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.event.before == '0000000000000000000000000000000000000000' && github.event.compare == 'https://github.com/${{ github.repository }}/compare/${{ github.sha }}' && regex_replace(github.ref, '^refs/tags/', '') || '' }}
          release_name: Release ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.event.before == '0000000000000000000000000000000000000000' && github.event.compare == 'https://github.com/${{ github.repository }}/compare/${{ github.sha }}' && regex_replace(github.ref, '^refs/tags/', '') || '' }}
          body: |
            Changes in this Release:
            - ...
          draft: false
          prerelease: false
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: packed-solution
          path: out/
          


  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: your-artifact-name
  #         path: ./dist/*.tgz  # Adjust the path based on your project structure
